### ISSUE TITLE
Error file missing when running export

### ISSUE THREAD

**Issue by maxzw** [miselico/graph_query_sampler#34]
script: 

gqs export to-kgreasoning --dataset aifb
error:
File "d:\thesis_code\graph_query_sampler\src\gqs\export.py", line 93, in zero_qual_queries_dataset_to_KGReasoning
    with open(stats_output_location) as open_stats_output:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\thesis_code\\graph_query_sampler\\datasets\\aifb\\export\\kgreasoning\\stats.txt'

Solution:
export.py line 93, add 'w' to open():
        with open(stats_output_location, 'w') as open_stats_output:

**Comment by maxzw** [comment]
in branch 'generic-triple-store' btw

**Comment by miselico** [comment]
fixed in 1bffc430e7e478950cad3719454e3ffb0b052a12 'generic-triple-store' has been merged into main.
